name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Debug Version with Gradle
        run: ./gradlew assembleDebug # 懒得搞签名了，直接用Debug包吧
      - name: Move Apks to current Directory
        run: find app/build -name "*.apk" -type f| xargs -I {} mv {} ./
      - name: Publish snapshot version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Build"
          files: |
            README.md
            *.apk